### ISSUE TITLE
엑박 상태인 이미지가 있습니다.

### ISSUE THREAD

**Issue by ninezero90hy** [cheese10yun/IntelliJ#1]
- **plugin/Assistant-Properties.md**
  - `Properties 속성이 코드에 바인딩 되는지 확인 할 수 있어 아주 유용합니다.` 
  해당 글에 대한 설명 이미지가 엑박 상태 입니다.

- **Additional context**
<img width="936" alt="2019-01-29 1 19 07" src="https://user-images.githubusercontent.com/41019113/51849905-ff17e000-2363-11e9-9dbf-32eb4280ceaa.png">

**Comment by cheese10yun** [comment]
넵 수정 완료했습니다. 감사합니다.
